name: Build and Release

on:
 workflow_dispatch:

jobs:
 apk:
   name: Generate APK
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2.4.0
     - name: Build Signed APK
       # You may pin to the exact commit or the version.
       # uses: victorbnl/build-signed-apk@131e59d4deaf2fb9d2aadb555b2ac131affeef5f
       uses: victorbnl/build-signed-apk@v1.0.0
       with:
         # Keystore file encoded as base64
         keystore: ${{ secrets.keystore }}
         # Keystore file password
         keystore_password: ${{ secrets.keystore_password }}
         # Key alias
         key_alias: ${{ secrets.key_alias }}
         # Key password
         key_password: ${{ secrets.key_password }}
         
     - name: Push
       uses: ad-m/github-push-action@v0.6.0
       with:
         github_token: $\{{ secrets.GITHUB_TOKEN }}
