name: Build and Release

on:
 workflow_dispatch:

jobs:
 apk:
   name: Generate APK
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2.4.0
      
     - uses: r0adkll/sign-android-release@v1
       name: Sign app APK
       # ID used to access action output
       id: sign_app
       with:
         releaseDirectory: app/build/outputs/apk/release
         signingKeyBase64: ${{ secrets.keystore }}
         alias: ${{ secrets.key_alias }}
         keyStorePassword: ${{ secrets.keystore_password }}
         keyPassword: ${{ secrets.key_password }}
       env:
         # override default build-tools version (29.0.3) -- optional
         BUILD_TOOLS_VERSION: "30.0.2"
         
     - uses: ShaunLWM/action-release-debugapk@master
       env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
         APP_FOLDER: ${{steps.sign_app.outputs.signedReleaseFile}}
         RELEASE_TITLE: New Build
