name: Build and Release

on:
 workflow_dispatch:

jobs:
 apk:
   name: Generate APK
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2.4.0
       
     - name: Build Android App
       uses: sparkfabrik/android-build-action@v1.4.0
       with:
         project-path: .
         output-path: app/build/outputs/apk/release
         gradle-task: assemble
         
     - uses: r0adkll/sign-android-release@v1
       name: Sign app APK
       # ID used to access action output
       id: sign_app
       with:
         releaseDirectory: app/build/outputs/apk/release
         signingKeyBase64: ${{ secrets.keystore }}
         alias: ${{ secrets.key_alias }}
         keyStorePassword: ${{ secrets.keystore_password }}
         keyPassword: ${{ secrets.key_password }}
       env:
         # override default build-tools version (29.0.3) -- optional
         BUILD_TOOLS_VERSION: "30.0.2"
         
     - name: Git Commit Push Action
       # You may pin to the exact commit or the version.
       # uses: GuillaumeFalourd/git-commit-push@205c043bca2f932f7a48a28a8d619ba30eb84baf
       uses: GuillaumeFalourd/git-commit-push@v1.3
       with:
         access_token: $\{{ secrets.GITHUB_TOKEN }}
